from abc import ABC, abstractmethod
from typing import Any
import numpy as np

class Agent(ABC):
    @abstractmethod
    def act(self, state: np.ndarray) -> int: ...
    @abstractmethod
    def remember(self, s, a, r, s2, done): ...
    @abstractmethod
    def train_step(self): ...
    @abstractmethod
    def save(self, path: str): ...
    @abstractmethod
    def load(self, path: str): ...
